### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by aibi786** [evanc577/download-iglive#1]
program isn't installing
i downloaded the .exe file for windows pc
windows 10
and when i click on exe file to install nothing happens and i also tried to run it with administrator permissions but again nothing happened

**Comment by evanc577** [comment]
The provided .exe is not an installer, it should be run directly from the command line as shown in the README.

Also, the program has only been tested on Linux, the Windows and MacOS builds are completely untested.

**Comment by aibi786** [comment]
which linux distro?

**Comment by aibi786** [comment]
> The provided .exe is not an installer, it should be run directly from the command line as shown in the README.
> 
> Also, the program has only been tested on Linux, the Windows and MacOS builds are completely untested.

which linux distro?
