### ISSUE TITLE
Don't call `unwrap` on `stdin.write_all`

### ISSUE THREAD

**Issue by AlexGuo1998** [evanc577/download-iglive#3]
When I try to download or merge a live video, I got a lot of panics like:

```text
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /github/workspace/src/pts.rs:23:38
```

https://github.com/evanc577/download-iglive/blob/3dd39cb7832e0e90b45a7972aba239df7b9489e0/src/pts.rs#L23

It seems like if `ffprobe` can parse the information without reading the whole file, it would close the `stdin` early, causing this panic.

I don't know if it's correct to completely ignore this `Err`, but can we safely ignore this "broken pipe" variant?

**Comment by evanc577** [comment]
Thanks, this should be fixed in v0.1.5
